#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")"

npm install
typescript=./node_modules/typescript/lib

rm -f -r ../Build

echo $(tput bold)Building Debug$(tput sgr0)
mkdir -p ../Build/Debug
wrap="--wrap=0"
if [ $(uname -s) = "Darwin" ]; then
    wrap=""
fi
cp ../Source/index.html ../Build/Debug/index.html
cat << EOF >> ../Build/Debug/data.ts
var spriteImageData = "$(base64 ../Source/Sprite.gif ${wrap})";
var fontImageData = "$(base64 ../Source/Font.gif ${wrap})";
var diamondSoundData = "$(base64 ../Source/Diamond.wav ${wrap})";
var stoneSoundData = "$(base64 ../Source/Stone.wav ${wrap})";
var stepSoundData = "$(base64 ../Source/Step.wav ${wrap})";
EOF
node ${typescript}/tsc.js -target ES5 -out ../Build/Debug/digger.js ./libex.d.ts ../Source/*.ts ../Build/Debug/data.ts
rm ../Build/Debug/data.ts

echo $(tput bold)Building Release$(tput sgr0)
mkdir -p ../Build/Release
cp ../Source/index.html ../Build/Release/index.html
node minify.js ../Build/Debug/digger.js ../Build/Release/digger.js